version: 2.1

download: &download
  steps:
    - checkout
    - run:
        name: "Download dependencies"
        command: "go get -d -t ./..."
    - run:
        name: "Download staticcheck"
        command: "go get honnef.co/go/tools/cmd/staticcheck"
    - run:
        name: "Download go-junit-report"
        command: "go get github.com/jstemmer/go-junit-report"
    - persist_to_workspace:
        root: "/go/"
        paths:
          - "src/*"
          - "bin/staticcheck"
          - "bin/go-junit-report"

gofmt: &gofmt
  steps:
    - attach_workspace:
        at: "/go/"
    - run:
        name: "gofmt"
        command: "[ -z \"$(gofmt -l .)\" ] || exit $?"

test: &test
  steps:
    - attach_workspace:
        at: "/go/"
    - run:
        name: "Run tests"
        command: "go test -parallel=2 -v ./... >/tmp/test.out"
    - run:
        name: "Process test results"
        when: always
        command: |
          mkdir -p /tmp/test-results/go-test
          go-junit-report < /tmp/test.out > /tmp/test-results/go-test/results.xml
          cat /tmp/test.out
    - store_test_results:
        path: "/tmp/test-results"

vet: &vet
  steps:
    - attach_workspace:
        at: "/go/"
    - run:
        name: "Run go vet"
        command: "go vet ./..."

staticcheck: &staticcheck
  steps:
    - attach_workspace:
        at: "/go/"
    - run:
        Name: "Run staticcheck"
        command: "staticcheck -go 1.11 ./..."

executors:
  go11:
    docker:
      - image: "circleci/golang:1.11.9"
    working_directory: "/go/src/honnef.co/go/tools"
  go12:
    docker:
      - image: "circleci/golang:1.12.5"
    working_directory: "/go/src/honnef.co/go/tools"

jobs:
  download12:
    executor: go12
    <<: *download
  gofmt12:
    executor: go12
    <<: *gofmt
  test12:
    executor: go12
    <<: *test
  vet12:
    executor: go12
    <<: *vet
  staticcheck12:
    executor: go12
    <<: *staticcheck

  download11:
    executor: go11
    <<: *download
  gofmt11:
    executor: go11
    <<: *gofmt
  test11:
    executor: go11
    <<: *test
  vet11:
    executor: go11
    <<: *vet
  staticcheck11:
    executor: go11
    <<: *staticcheck


workflows:
  version: 2
  ci12:
    jobs:
      - download12
      - gofmt12:
          requires:
            - download12
      - test12:
          requires:
            - download12
      - vet12:
          requires:
            - download12
      - staticcheck12:
          requires:
            - download12
  ci11:
    jobs:
      - download11
      - gofmt11:
          requires:
            - download11
      - test11:
          requires:
            - download11
      - vet11:
          requires:
            - download11
      - staticcheck11:
          requires:
            - download11
