name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-amd64
          - linux-386
          - darwin-amd64
          - darwin-arm64
          - windows-amd64
          - linux-arm
          - linux-arm64
          - linux-ppc64le
          - linux-s390x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.8"
      - env:
          TARGET: ${{ matrix.target }}
        run: |
          echo "${TARGET}"
          case "${TARGET}" in
            linux-amd64)
              ARCH=amd64 PASSES='build' ./scripts/test.sh
              ;;
            linux-386)
              ARCH=386 PASSES='build' ./scripts/test.sh
              ;;
            darwin-amd64)
              ARCH=amd64 GOOS=darwin GO_BUILD_FLAGS='-v -mod=readonly' ./scripts/build.sh
              ;;
            darwin-arm64)
              ARCH=arm64 GOOS=darwin GO_BUILD_FLAGS='-v -mod=readonly' ./scripts/build.sh
              ;;
            windows-amd64)
              ARCH=amd64 GOOS=windows GO_BUILD_FLAGS='-v -mod=readonly' ./scripts/build.sh
              ;;
            linux-arm)
              ARCH=arm GO_BUILD_FLAGS='-v -mod=readonly' ./scripts/build.sh
              ;;
            linux-arm64)
              ARCH=arm64 GO_BUILD_FLAGS='-v -mod=readonly' ./scripts/build.sh
              ;;
            linux-ppc64le)
              ARCH=ppc64le GO_BUILD_FLAGS='-v -mod=readonly' ./scripts/build.sh
              ;;
            linux-s390x)
              ARCH=s390x GO_BUILD_FLAGS='-v -mod=readonly' ./scripts/build.sh
              ;;
            *)
              echo "Failed to find target"
              exit 1
              ;;
          esac

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        go: ["1.17.8"]
    env:
      GIT_ORG: ${{ github.repository_owner }}
      GIT_REPO: ${{ github.events.repository.name }}
      GO_VERSION: ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
    # This step is required as long as the symlinks for client/v3/*_test.go -> tests/integration/clientv3/examples/*_test.go exist
      - name: core.symlinks
        run: |
          git config --global core.symlinks true
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1      
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{ matrix.go }}
      - name: Continuous Integration
        run: make.ps1 -Script ci # -Version ${{ github.ref }}
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
          install-go: false
          cache-key: ${{ matrix.go }}