name: E2E-arm64
on:
  schedule:
    - cron: '0 1 * * *' # runs daily at 1am.
permissions: read-all
jobs:
  test:
    # this is to prevent the job to run at forked projects
    if: github.repository == 'etcd-io/etcd'
    runs-on: [Linux, ARM64]
    strategy:
      fail-fast: true
      matrix:
        target:
        - linux-arm64-e2e
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        ref: main
        go-version: "1.19.7"
    - run: date
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        set -euo pipefail

        echo "${TARGET}"
        case "${TARGET}" in
          linux-arm64-e2e)
            PASSES='build release e2e' CPU='4' EXPECT_DEBUG='true' COVER='false' RACE='true' ./scripts/test.sh
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
