name: E2E-arm64
on:
  schedule:
    - cron: '0 1 * * *' # runs daily at 1am.
permissions: read-all
jobs:
  test:
    # this is to prevent the job to run at forked projects
    if: github.repository == 'etcd-io/etcd'
    runs-on: [Linux, ARM64]
    strategy:
      fail-fast: true
      matrix:
        target:
        - linux-arm64-e2e
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        ref: main
        go-version: "1.19.7"
    - run: date
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        set -euo pipefail

        echo "${TARGET}"
        case "${TARGET}" in
          linux-arm64-e2e)
            PASSES='build release e2e' CPU='4' EXPECT_DEBUG='true' COVER='false' RACE='true' ./scripts/test.sh
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
