name: E2E-arm64
on:
  schedule:
    - cron: '0 1 * * *' # runs daily at 1am.
permissions: read-all
jobs:
  goversion:
    uses: ./.github/workflows/go-version.yaml
  test:
    # this is to prevent the job to run at forked projects
    if: github.repository == 'etcd-io/etcd'
    runs-on: [Linux, ARM64]
    needs: goversion
    strategy:
      fail-fast: true
      matrix:
        target:
        - linux-arm64-e2e
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        ref: main
        go-version: ${{ needs.goversion.outputs.goversion }}
    - run: date
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        set -euo pipefail

        echo "${TARGET}"
        case "${TARGET}" in
          linux-arm64-e2e)
            GOOS=linux GOARCH=arm64 CPU=4 EXPECT_DEBUG=true RACE=true make test-e2e-release
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
