name: E2E
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
        - linux-amd64-e2e
        - linux-386-e2e
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: "1.16.15"
    - run: date
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        echo "${TARGET}"
        case "${TARGET}" in
          linux-amd64-e2e)
            PASSES='build release e2e' MANUAL_VER=v3.4.7 CPU='4' EXPECT_DEBUG='true' COVER='false' RACE='true' ./test.sh 2>&1 | tee test.log
            ! egrep "(--- FAIL:|DATA RACE|panic: test timed out|appears to have leaked)" -B50 -A10 test.log
            ;;
          linux-386-e2e)
            GOARCH=386 PASSES='build e2e' CPU='4' EXPECT_DEBUG='true' COVER='false' RACE='true' ./test.sh 2>&1 | tee test.log
            ! egrep "(--- FAIL:|DATA RACE|panic: test timed out|appears to have leaked)" -B50 -A10 test.log
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
