name: Fuzzing v3rpc
on: [push, pull_request]
permissions: read-all
jobs:
  goversion:
    uses: ./.github/workflows/go-version.yaml
  fuzzing:
    runs-on: ubuntu-latest
    needs: goversion
    strategy:
      fail-fast: false
    env:
      TARGET_PATH: ./server/etcdserver/api/v3rpc
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version: ${{ needs.goversion.outputs.goversion }}
    - run: |
        set -euo pipefail

        GOARCH=amd64 CPU=4 make fuzz
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      if: failure()
      with:
        path: "${{env.TARGET_PATH}}/testdata/fuzz/**/*"
