name: Fuzzing v3rpc
on: [push, pull_request]
permissions: read-all
jobs:
  fuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      TARGET_PATH: ./server/etcdserver/api/v3rpc
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
    - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
      with:
        go-version: "1.19.4"
    - run: GOARCH=amd64 CPU=4 make fuzz
    - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
      if: failure()
      with:
        path: "${{env.TARGET_PATH}}/testdata/fuzz/**/*"
