name: Go version setup

on:
  workflow_call:
    outputs:
      goversion:
        value: ${{ jobs.version.outputs.goversion }}

jobs:
  version:
    name: Set Go version variable for all the workflows
    runs-on: ubuntu-latest
    outputs:
      goversion: ${{ steps.goversion.outputs.goversion }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - id: goversion
        run: |
          GO_VERSION=$(cat .go-version)
          echo "Go Version: $GO_VERSION"
          echo "goversion=$GO_VERSION" >> $GITHUB_OUTPUT
