---
name: Robustness Nightly
permissions: read-all
on:
  # schedules always run against the main branch, hence we have to create separate jobs
  # with individual checkout actions for each of the active release branches
  schedule:
    - cron: '25 9 * * *' # runs every day at 09:25 UTC
jobs:
  main:
    # GHA has a maximum amount of 6h execution time, we try to get done within 3h
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: main
      count: 80
      testTimeout: 200m
      artifactName: main
      runs-on: "['ubuntu-latest-8-cores']"
  main-arm64:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: main
      count: 80
      testTimeout: 200m
      artifactName: main-arm64
      runs-on: "['self-hosted', 'Linux', 'ARM64']"
  release-35:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: release-3.5
      count: 80
      testTimeout: 200m
      artifactName: release-35
      runs-on: "['ubuntu-latest-8-cores']"
  release-35-arm64:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: release-3.5
      count: 100
      testTimeout: 200m
      artifactName: release-35-arm64
      runs-on: "['self-hosted', 'Linux', 'ARM64']"
  release-34:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: release-3.4
      count: 80
      testTimeout: 200m
      artifactName: release-34
      runs-on: "['ubuntu-latest-8-cores']"
