---
name: Mark and close stale issues and PRs

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d #v10.1.1
        with:
          days-until-stale: 90
          days-until-close: 21
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-labels: 'stage/tracked,help wanted'
          exempt-projects: false
          exempt-milestones: false
          exempt-assignees: false
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed after 21 days if no further activity occurs. Thank you for your contributions.'
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed after 21 days if no further activity occurs. Thank you for your contributions.'
          close-issue-message: ''
          close-pr-message: ''
          operations-per-run: 30
