---
name: Static Analysis
on: [push, pull_request]
permissions: read-all
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@5f1fec7010f6ae3b84ea4f7b2129beb8639b564f # v3.5.0
        with:
          version: v1.49.0
          args: --config tools/.golangci.yaml
      - name: protoc
        uses: arduino/setup-protoc@149f6c87b92550901b26acd1632e11c3662e381f # v1.3.0
        with:
          version: '3.14.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          set -euo pipefail

          make verify
      - run: |
          set -euo pipefail

          make fix
