name: Trivy Nightly Build Scan
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
permissions: read-all 
jobs:
  nightly-scan:
    name: Trivy Build Scan nightly
    strategy:
      fail-fast: false
      matrix:
        # maintain the versions of etcd that need to be actively
        # security scanned
        target:
          - amd64
          - arm64
          - ppc64le
          - s390x
    permissions:
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: release-3.5
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: "1.19.6"
      - run: |
            ./build.sh
            cp ./Dockerfile-release.${{ matrix.target }} ./bin/Dockerfile-release.${{ matrix.target }}
            docker build \
              --network=host \
              --tag gcr.io/etcd-development/etcd:${{ github.sha }}-${{ matrix.target }} \
              --file ./bin/Dockerfile-release.${{ matrix.target }} \
              ./bin
            rm -f ./bin/Dockerfile-release.${{ matrix.target }}
      - name: Trivy scan
        uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # 0.9.2
        with:
          image-ref: 'gcr.io/etcd-development/etcd:${{ github.sha }}-${{ matrix.target }}'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results-3-5-${{ github.sha }}-${{ matrix.target }}.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@e00cd12e3ee0ce24d476645336a315351be51d88 # v2.2.5
        with:
          sarif_file: 'trivy-results-3-5-${{ github.sha }}-${{ matrix.target }}.sarif'

